# Generated by Django 4.1.7 on 2023-03-22 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_email_contact_email_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
