# Generated by Django 4.1.7 on 2023-03-03 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversationmessage',
            old_name='content',
            new_name='cover_letter',
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='curriculum_vitae',
            field=models.FileField(default='0000.pdf', upload_to='cv_pdfs/'),
        ),
    ]
