# Generated by Django 4.1.7 on 2023-03-03 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='image',
            new_name='company_logo',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='description',
            new_name='job_description',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='name',
            new_name='job_title',
        ),
    ]
